### ISSUE TITLE
Allow to configure nftables chain priority

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/cs-firewall-bouncer#109]
We currently hardcode the chain priority to 0, and some users would like to be able to customize the priority.

Should we allow any arbitrary value or restrict ourselves to the priorities defined here: https://github.com/google/nftables/blob/master/chain.go#L48 ?

**Comment by pdf** [comment]
I think probably just allow arbitrary int32 - it's less complex to maintain, and it's more flexible for users.
