### ISSUE TITLE
Support deny_action: TARPIT

### ISSUE THREAD

**Issue by gloomytrousers** [crowdsecurity/cs-firewall-bouncer#127]
With [xtables-addons](https://sourceforge.net/projects/xtables-addons/) installed, there is a `TARPIT` target available in iptables. However, setting `deny_action: TARPIT` in crowdsec-firewall-bouncer.yaml is ignored - it defaults to DENY.

Please allow `TARPIT` as an accepted value for `deny_action`. Looks like [iptables.go](https://github.com/crowdsecurity/cs-firewall-bouncer/blob/main/iptables.go#L40) is the right place for this.

I'd also suggest it's better to fail with an error if the config contains an unsupported value, rather than silently picking a default - this will likely prevent a lot of head scratching.

**Comment by LaurenceJJones** [comment]
So we could have a slice of supported actions we check if value is in slice if not error on startup

https://github.com/crowdsecurity/cs-firewall-bouncer/blob/9f27212e5b1db022f27a61b401741d7f889985d2/pkg/iptables/iptables.go#L55-L60

**Comment by LaurenceJJones** [comment]
Will be released in next version

**Comment by gloomytrousers** [comment]
Just in case anyone stumbles upon this in future... despite the fix in this ticket, TARPIT doesn't work. The bouncer tries to set up an iptables rule for all protocols with TARPIT as the target, which results in "x_tables: ip_tables: TARPIT target: only valid for protocol 6" (i.e. TCP).
