### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by xgdgsc** [crowdsecurity/cs-firewall-bouncer#14]
```
[root@r4 cs-firewall-bouncer-v0.0.4]# ./install.sh 
which: no nft in (/opt/rh/devtoolset-4/root/usr/bin:/opt/rh/devtoolset-4/root/usr/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/sgao/.local/bin:/home/sgao/bin)
Installing firewall-bouncer
removed ‘/usr/local/bin/cs-firewall-bouncer’
‘./cs-firewall-bouncer’ -> ‘/usr/local/bin/cs-firewall-bouncer’
Error: unknown command "bouncers" for "cscli"
Run 'cscli --help' for usage.
FATA[0000] While executing root command : unknown command "bouncers" for "cscli" 
Job for cs-firewall-bouncer.service failed because the control process exited with error code. See "systemctl status cs-firewall-bouncer.service" and "journalctl -xe" for details.
The firewall-bouncer service has been installed!
```

**Comment by buixor** [comment]
Hello,

Can you tell me which distribution or environment you're using? I didn't manage to reproduce the issue.
(However, I'm fixing the fact that it's assuming by default that `cscli` is present on the same machine)

Thanks,

**Comment by xgdgsc** [comment]
CentOS Linux release 7.7.1908 (Core) . I' m using crowdsec v0.3.7 , do I need to install master?

**Comment by buixor** [comment]
Ah, `cs-firewall-bouncer` is intended for v1.X and further (https://github.com/crowdsecurity/crowdsec/releases) that is the next release (next week). If you want to use a firewall bouncer for 0.3.X, you should use [cs-netfilter-blocker](https://github.com/crowdsecurity/cs-netfilter-blocker) that only support iptables/ipset. 

You can find your relevant bouncers on the hub https://hub.crowdsec.net/browse/#bouncers and select your crowdsec version.

**Comment by xgdgsc** [comment]
Thanks!
