### ISSUE TITLE
crowdsec log filled with GET from firewall bouncer

### ISSUE THREAD

**Issue by youngt2** [crowdsecurity/cs-firewall-bouncer#154]
I have cs-firewall-bouncer installed in several locations all using the same LAPI. However, this means that my local crowdsec log is very crowded with lines like:
`time="09-03-2022 11:02:49" level=info msg="10.20.1.3 - [Wed, 09 Mar 2022 11:02:49 EST] \"GET /v1/decisions/stream?startup=false HTTP/1.1 200 10.689185ms \"crowdsec-firewall-bouncer/v0.0.22-debian-pragmatic-f64e94b59a948717c3dc848f9abebb27b5974714\" \""`
It is almost impossible to find anything useful in the log with all the additional noise from this bouncer. Can this log entry be disabled using a different log level?

**Comment by AlteredCoder** [comment]
Hello @youngt2 ,

Those logs are only the local API access log. The useful logs are written to `/var/log/crowdsec.log`.

**Comment by youngt2** [comment]
> Hello @youngt2 ,
> 
> Those logs are only the local API access log. The useful logs are written to `/var/log/crowdsec.log`.

Makes sense. Thank you for clarifying!

**Comment by youngt2** [comment]
> Hello @youngt2 ,
> 
> Those logs are only the local API access log. The useful logs are written to `/var/log/crowdsec.log`.
@AlteredCoder 
This file is always blank for me. I've tried both mounting it in my docker-compose and looking at it directly through `docker exec crowdsec cat /var/log/crowdsec.log`. The file seems to stay blank. Any ideas? Maybe I'm missing something obvious.
