### ISSUE TITLE
Package not available on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by peg-leg** [crowdsecurity/cs-firewall-bouncer#167]
I'm running Ubuntu 18.04 LTS and getting
E: Unable to locate package crowdsec-firewall-bouncer-iptables 
when attempting to install using
apt install crowdsec-firewall-bouncer-iptables

Is there a repo I need to add?

**Comment by stratege1401** [comment]
Hi,

Have you tried :
`curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash`
`apt-get update`
`apt-get install crowdsec`

**Comment by timtait** [comment]
Had the same error, adding the repository fixes it

**Comment by AlteredCoder** [comment]
Yes, you need to add crowdsec repositories to have the package available.
