### ISSUE TITLE
script set nftables whatever the firewall installed

### ISSUE THREAD

**Issue by dnit71** [crowdsecurity/cs-firewall-bouncer#17]
Hello,
When I run the script install.sh, the firewall nftables is set but it is not installed, the command which nft returns nothing. The command _which iptables_ return the path ,so the variable  $? return "0". I don't understand why the script choose nftables. I Tried to modify the config file cs-firewall-bouncer.yaml in /etc/crowdsec/cs-firewall-bouncer with mode: iptables but the service doesn't want to start.

**Comment by dnit71** [comment]
I modified the default firewall to iptables and now when I run the script it display that ipset is not installed.

**Comment by buixor** [comment]
Hello,

Did you use the release or directly the main branch ?
We were doing some improvements on the install script but didn't release yet (just to know with which one to reproduce).

For the second issue : when using iptables mode, it will require ipset to maintain the list of tables.

thanks,

**Comment by dnit71** [comment]
Hello,
I answered too fast. When I saw the message about ipset, I installed it and now it's working correctly with Iptables (it's nnot a second problem). I used the release with a _wget https://github.com/crowdsecurity/cs-firewall-bouncer/releases/download/v0.0.5/cs-firewall-bouncer.tgz_. I will try with the new release.

**Comment by buixor** [comment]
Cool, keep me posted !

**Comment by dnit71** [comment]
Hello,
I update the bouncer to the v.0.0.6 and it's working fine.
