### ISSUE TITLE
Add support for ufw

### ISSUE THREAD

**Issue by miny1997** [crowdsecurity/cs-firewall-bouncer#175]
Please add support for ufw, which is a easy-to-use firewall used by a lot of server admins. https://en.wikipedia.org/wiki/Uncomplicated_Firewall

**Comment by buixor** [comment]
Hello,

as ufw seems to be using iptables at the back, I'm not sure it would even require some extra configuration.
did you try it ? and/or what makes you believe some extra actions are needed to support it ?

thanks,

**Comment by miny1997** [comment]
I did not install the software yet as my team is really busy and I am doing my research which software we need for our server. The reason I think an implementation for ufw makes sense is that the changes Crowdsecurity does to  ufw would be more accessible for less tech-savy users because ufw is way easier to use than iptables.

Using iptables beside ufw would theoretically work, but for those who do not use iptables, it would be a black box.

**Comment by ovizii** [comment]
There was a post about a year ago about some issues: https://github.com/crowdsecurity/cs-firewall-bouncer/issues/46

It would be nice if somebody more knowledgeable would confirm if there are any issues using cs-firewall-bouncer and UFW together or if there are any interferences.

**Comment by floari** [comment]
As UFW is just an interface for iptables it is running as expected (both services just add chains to the fw).
