### ISSUE TITLE
Add the possibility to choose an alternate or additional chain for the iptables rule

### ISSUE THREAD

**Issue by chris968** [crowdsecurity/cs-firewall-bouncer#19]
That would be great if you add the possibility to choose an alternate or additional chain for the iptables rule. 

e.g. docker containers are not protected by crowsded by default, the rule need to be inserted into the DOCKER-USER or FORWARD chain.

**Comment by bilange** [comment]
In case somebody needs a quick fix, here's what I did to point cs-firewall-bouncer to the DOCKER-USER chain. (I assume this might be incompatible with the upgrade.sh script- untested.)

1. We're building from source, according to the docs in the readme of this repo. See the section "From source".
2. git clone https://github.com/crowdsecurity/cs-firewall-bouncer.git
3. What the doc didn't specify is that you need at least the packages golang and make (and others???) installed. On my Ubuntu Server installation, this was resolved quickly by typing `sudo apt install golang build-essential`, but you might want to replace build-essential for only the tools cs-firewall-bouncer needs for compilation. I didn't take the time to fine-tune to find all the packages.
4. BEFORE typing `make release`, edit `iptables.go` and look for the lines around lines 25 (for the future readers: lookup for the lines starting with StartupCmds, ShutdownCmds, CheckIptableCmds) that has "INPUT" on it. Replace INPUT for your needed chain (ex: "DOCKER-USER") - leave the rest of the lines unchanged. 
4b. IPv6: search for the same StartupCmds/ShutdownCmds/CheckIptableCmds lines again, these are defined further down for IPv6. At the time of the writing, those are on the lines 50-52.
5. `make release` and proceed to the rest of the source installation as the readme describes.

**Comment by buixor** [comment]
Yes, that's a great suggestion and overdue, I've started a MR to deal with this : https://github.com/crowdsecurity/cs-firewall-bouncer/pull/20

**Comment by buixor** [comment]
This MR should allow configuring 0 or more iptables chains in which the rules are going to be inserted. (If there are none, only the ipset sets will be maintained).

@chris968 is it what you were looking for ? :)

cheers,

**Comment by chris968** [comment]
Yes, we need to be able to configure several chains if needed.

**Comment by buixor** [comment]
yep, should be the case ! it has been merged in the release candidate v0.0.7

**Comment by chris968** [comment]
Working great, it might throw error if you use mixed IPv4/IPv6 environment and a required chain didn't exist for both stack (e.g. docker's chains) but I've manage to bypass the problem by creating an empty chain for IPv6.
