### ISSUE TITLE
Package not available on Fedora 36

### ISSUE THREAD

**Issue by Wotisrv** [crowdsecurity/cs-firewall-bouncer#193]
Hei,
currently installed Crowdsec by issuing:
`curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh | sudo bash`
`dnf install crowdsec`

But cannot find crowdsec-firewall-bounce-iptables:
`dnf install crowdsec-firewall-bouncer-iptables`
`crowdsec_crowdsec                                                                               931  B/s | 1.8 kB     00:02`
`crowdsec_crowdsec-source                                                                        951  B/s | 1.8 kB     00:01`
`No match for argument: crowdsec-firewall-bouncer-iptables`
`Error: Unable to find a match: crowdsec-firewall-bouncer-iptables`

System Fedora Linux 36 - Server Edition

**Comment by Wotisrv** [comment]
Case can be closed. Need to download manually. 👍

**Comment by fabzo** [comment]
@Wotisrv I'm having the same issue. Are you saying that it isn't expected to be available for Fedora 36? Since crowdsec itself is.

**Comment by Wotisrv** [comment]
The installation instructions do not indicate that crowdsec-firewall-bouncer must be downloaded separately from `https://github.com/crowdsecurity/cs-firewall-bouncer/releases/download/v0.0.23/crowdsec-firewall-bouncer.tgz`
Following the guide you can expect it to install via dnf/yum as you should just run `dnf install crowdsec-firewall-bouncer-iptables`

**Comment by Wotisrv** [comment]
Installed it today. 
`# dnf install crowdsec-firewall-bouncer-iptables-0.0.24-1.fc36.x86_64 -y
Last metadata expiration check: 0:03:32 ago on Sat Oct 15 13:15:59 2022.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                                            Architecture                           Version                                         Repository                                         Size
===================================================================================================================================================================================================================
Installing:
 crowdsec-firewall-bouncer-iptables                                 x86_64                                 0.0.24-1.fc36                                   crowdsec_crowdsec                                 2.9 M

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total download size: 2.9 M
Installed size: 8.4 M
Downloading Packages:
crowdsec-firewall-bouncer-iptables-0.0.24-1.fc36.x86_64.rpm                                                                                                                        695 kB/s | 2.9 MB     00:04    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                              695 kB/s | 2.9 MB     00:04     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Installing       : crowdsec-firewall-bouncer-iptables-0.0.24-1.fc36.x86_64                                                                                                                                   1/1 
warning: /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml created as /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml.rpmnew

  Running scriptlet: crowdsec-firewall-bouncer-iptables-0.0.24-1.fc36.x86_64                                                                                                                                   1/1 
cscli/crowdsec is present, generating API key
API Key : ae65c649532dc14a646b82328f49c2e1

  Verifying        : crowdsec-firewall-bouncer-iptables-0.0.24-1.fc36.x86_64                                                                                                                                   1/1 

Installed:
  crowdsec-firewall-bouncer-iptables-0.0.24-1.fc36.x86_64                                                                                                                                                          

Complete!`

As showed in the table there is no information about IP adress, type and version for FirewallBouncer-1665832777.
Is that right this way?

`# cscli bouncers list
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 NAME                          IP ADDRESS  VALID  LAST API PULL         TYPE                       VERSION                                           AUTH TYPE 
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 cs-firewall-bouncer-eisXX6Jl  127.0.0.1   ✔️      2022-10-15T11:26:25Z  crowdsec-firewall-bouncer  v0.0.23-5a27e28ac5b528ab02fc35ae81459f75f69a3866  api-key   
 FirewallBouncer-1665832777                ✔️      2022-10-15T11:19:37Z                                                                               api-key   
---------------------------------------------------------------------------------------------------------------------------------------------------------------`

**Comment by LaurenceJJones** [comment]
Most likely would fail to run if you already have a firewall bouncer installed. But if it was the only one it would of created api key and started
