### ISSUE TITLE
cs-firewall-bouncer.log fork/exec /sbin/ipset: too many open files

### ISSUE THREAD

**Issue by devefrogg** [crowdsecurity/cs-firewall-bouncer#207]
Sous ubuntu ulimit file est par défaut a 1024; en cas de multiple attaque cette limite est vite atteinte ... c'est du vécu .. Le firewall ne récupère plus les consignes de crowdsec et cesse de foncionner ... 

```
time="31-07-2022 05:56:00" level=info msg="Error while deleting from set (/sbin/ipset -exist del crowdsec-blacklists W.X.Y.Z): fork/exec /sbin/ipset: too many open files --> "
```

J'ai contournais cette limite en rajoutant  LimitNOFILE=65536 dans la conf du service . 
```
[Unit]
Description=The firewall bouncer for CrowdSec
After=syslog.target network.target remote-fs.target nss-lookup.target crowdsec.service

[Service]
Type=notify
ExecStart=${BIN} -c ${CFG}/cs-firewall-bouncer.yaml
ExecStartPost=/bin/sleep 0.1
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

et bien mette une rotation de log sur ce fichier en plus .

**Comment by mmetc** [comment]
Merci @devefrogg !
