### ISSUE TITLE
feature-request: saner nftables chain priority  and counter

### ISSUE THREAD

**Issue by zxyz** [crowdsecurity/cs-firewall-bouncer#210]
Hello,
thanks for crowdsec and the bouncer. 

I have to two options I'd really like to have configurable in nftables, Atm I work with "set-only: true" which is great but quite some work.

## chain priority
The default created chains are e. g.:

```
	chain crowdsec6-chain {
		type filter hook input priority filter; policy accept;
		ip6 saddr @crowdsec6-blacklists drop
	}
```

priority `filter`is "0" and this is the priority used by many people and FW frameworks. If two chains have the same priority in nftables it's not deterministic which is used first. E. g. sshguard therefore uses:

```
	chain blacklist {
		type filter hook input priority filter - 10; policy accept;
		ip6 saddr @attackers drop
	}
```
to have its chains processes before the "normal" filter priority.

Making the priority configurable and have it set to a imho saner default of e .g. "-10" would be great.

This is not a security issue, because nftables behaves quite unintuitive if multiple chains are present with the same hook and family and "first-match" only applies for DROP rules (see https://github.com/openwrt/openwrt/issues/9981 for details).

## counter
It'd be great to have the option to easily get counters for the drop rules:
```
- ip6 saddr @crowdsec6-blacklists drop
+ ip6 saddr @crowdsec6-blacklists counter drop
```
to see if a DoS is happening or things are out of normal but where no logging is needed.

Thanks a lot!

**Comment by sbs2001** [comment]
@zxyz  thanks for feature request. The counter feature is included in upcoming release and we have a patch to add priority option now.
