### ISSUE TITLE
firewall-bouncer dies after boot

### ISSUE THREAD

**Issue by bernhara** [crowdsecurity/cs-firewall-bouncer#217]
On all my instances (X86-64 & Arm), I mentioned that the FW bounce dies immediately after the host has booted.

Reason: the network (DNS???) is not really ready and the DNS lookup for the CS host fails.
Instead of making multiple tries, the bouncer dies after the first check and is never reactivated (even by systemd).

This is very dangerous in my mind, since I didn't find yet a very simple way to be notified that a bouncer is no more alive.

```time="17-11-2022 11:45:30" level=info msg="Using API key auth"
time="17-11-2022 11:45:30" level=info msg="Processing new and deleted decisions . . ."
time="17-11-2022 11:45:30" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp: lookup XXXXXXXXX on  [::1]:53: server misbehaving"
time="17-11-2022 11:45:30" level=error msg="Get \"http://(HIDDEN):38080/v1/decisions/stream?startup=true\": dial tcp: lookup (HIDDEN).
home on [::1]:53: server misbehaving"
time="17-11-2022 11:45:30" level=error msg="terminating bouncer process"
```

**Comment by LaurenceJJones** [comment]
What DNS service are you running? I'm guessing not systemd-resolve. If it is classed as a systemd service you can edit the service file to boot after the dns service is up and running.
