### ISSUE TITLE
Ubuntu 18.04 service not starting

### ISSUE THREAD

**Issue by derritter88** [crowdsecurity/cs-firewall-bouncer#223]
Hi there,

I installed crowdsec & crowdsec-firewall-bouncer on a Ubuntu 18.04 server.
Unfortunately the service is not able to start and I get following error
```
crowdsec-firewall-bouncer[8325]: time="22-12-2022 21:59:42" level=fatal msg="iptables init failed: while inserting set in iptables: exit status 1"
```

If I check via `iptables -L` I do see that there is a block rule
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             match-set crowdsec-blacklists src
```

On an Ubuntu 22.04 machine it works without any issues.

Any ideas what's wrong?

**Comment by floari** [comment]
Hi,

I have the exact same problem on Debian 11. Same Error.

Thanks!

**Comment by derritter88** [comment]
@floari Thanks for the info.
On my Ubuntu 18.04 I already had IPv6 disabled via grub config - still not working

**Comment by floari** [comment]
@derritter88  Did you disable it in the bouncer config file? That did the trick.

**Comment by derritter88** [comment]
@floari Thanks!! That did the trick.
