### ISSUE TITLE
Docker Chain and ipv6 not starting

### ISSUE THREAD

**Issue by floari** [crowdsecurity/cs-firewall-bouncer#227]
Hi,

when enabling ipv6, INPUT and DOCKER-USER chain the bouncer is not starting.
Error: crowdsec-firewall-bouncer[8325]: time="22-12-2022 21:59:42" level=fatal msg="iptables init failed: while inserting set in iptables: exit status 1"

When disabling ipv6 everything is working as expected. Is ipv6 generally not compatible with docker?

Thanks!

**Comment by LaurenceJJones** [comment]
Docker tries to detect if you machine has IPv6 if it does not it doesnt create the IPv6 chain. You might need to enable it within the docker configuration if you machine does have ipv6.

**Comment by floari** [comment]
Machine has ipv6 enabled, docker does not. As I understand, my INPUT chain now only gets populated with ipv4 and not ipv6. Is there any way to split ipv4/ipv6 enabling between docker-user and input chains?

**Comment by LaurenceJJones** [comment]
You are correct, there is no current feature that allows you to do that. However, this issue has raised before and they switched to ipset only and wrote custom iptables rules.

What are you hosting within docker? for me personally I used nginx (bare metal) to reverse proxy to docker container (listening on loopback). However, I know an issue can arised like this if you use (nginx proxy manager, traefik) cause they come inside containers and bind to port 80,443 that chain is needed.

**Comment by floari** [comment]
Thanks for the input.
I use Traefik as proxy - ports 80 and 443 are of course bound to traefik.

**Comment by LaurenceJJones** [comment]
Stale issue and not much we can do since you need to configure docker to support ipv6
