### ISSUE TITLE
network adapter renamed after installation and shutdown/boot

### ISSUE THREAD

**Issue by akrea** [crowdsecurity/cs-firewall-bouncer#228]
Hi

Following setting: Ubuntu Server 22.04 latest patches. About 45 dockerised services.

I observed following behaviour: After installation of cs-firewall-bouncer and a shutdown/start few days later, the network adapter got renamed. Hence no internet connection.

Additional information: After installation of cs-firewall-bouncer I did not do any work on my server. I also did not reboot it. Today I shut down my server for HW-maintenance (and removal of graphics card). After boot my network was down as the network adapter got renamed. So I have no certainty that the installation caused this problem. To me it seems the most obvious cause. I did not try to recreate it.

For me this issue is solved - it is meant as an info for you developers in case anyone reports the same problem. I will report back if I encounter the issue again/find more info.

**Comment by LaurenceJJones** [comment]
Hey thank you for bringing this to light. There nothing in the package that should directly interact with interfaces but we will keep this in mind if it arises again!
