### ISSUE TITLE
State-tracking

### ISSUE THREAD

**Issue by hoerup** [crowdsecurity/cs-firewall-bouncer#232]
I would like for firewall bouncer to have the option for allowing inbound packages relating to allready established (outbound) connections

eg a enable_state_tracking option that when enabled starts with injecting a 
iptables --append INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

**Comment by LaurenceJJones** [comment]
Then best way would be switch the mode to `ipset` and then create the firewall rules yourself. As the firewall bouncer will always prepend the chains with the drop rule.
