### ISSUE TITLE
opnsense: time between decision and bouncer block takes way too long (+15min)

### ISSUE THREAD

**Issue by a1ad** [crowdsecurity/cs-firewall-bouncer#233]
Test enviroment: opnsense
Version: v1.4.3-8a738f5b
Bouncer: crowdsec-firewall-bouncer

when i remove a decision it takes +15min before the bouncer actually removes the ban.
```
cscli decisions remove -i *****
INFO[04-03-2023 02:54:35 PM] 1 decision(s) deleted  

Bouncer log:
time="04-03-2023 15:09:03" level=info msg="1 decision deleted"
```

The second bouncer on the lapi is a openrestybouncer and is reacting instant.

It is the same with a new decision to block: pf-fw-bouncers takes a long time and openresty is instant.

Logline that needs to get blocked:

`Telenet		2023-03-04T22:29:48	94.102.61.4:50339	84.192.*.*:10065	tcp	Default deny / state violation rule`

Detected and banned by Crowdsec:

`│ 3108148 │ crowdsec │ Ip:94.102.61.4     │ a1ad/pf-detect-blocked │ ban    │ NL      │ 202425 IP Volume inc                   │ 1      │ 3h59m46.154358211s │ 751      │
`

it takes +12min!! before the decision is added to the bouncer.

`time="04-03-2023 22:42:22" level=info msg="3 decisions added"`

After 12min the attacker gained access and what not so the Crowdsec protection is useless right now.

**Comment by LaurenceJJones** [comment]
Inside the bouncer configuration what is the update frequency?

https://github.com/crowdsecurity/cs-firewall-bouncer/blob/9aebcfbf0884a5d6ed12f741fad180dd9a7208fb/config/crowdsec-firewall-bouncer.yaml#L3

If this is the same as the default, is there anything that may be intercepting the request and making it take longer? as the lapi will not recall the endpoint unless the request finished.

**Comment by a1ad** [comment]
Default: 10sec, nothing in between that can intercept the requests. After a while the updates are instant. I have noticed that the bouncer is using 100% of the CPU after restart for a while (don't know how long) maybe that is why the update reaction is also so slow. It looks like the updates take place when the CPU consumption is settled. I need to do more tests to see if there is a correlation.

**Comment by a1ad** [comment]
I did some more testing after updating to the latest release (opnsense and Crowdsec)

Restarted Crowdsec on opnsense on 10:35
`time="08-03-2023 10:35:26" level=info msg="Crowdsec v1.4.6-freebsd-c8cb9ac9"`

Decision added at 10:37
`time="08-03-2023 10:37:19" level=info msg="Decision successfully added"`

High CPU usage after Crowdsec restart from 10:35 until 10:47

![image](https://user-images.githubusercontent.com/29516835/223680200-5efb71bd-3358-4add-95ac-e95709c3d44c.png)


Decisions are added to opnsense bouncer after the high CPU usage (30-50%) .

```
time="08-03-2023 10:47:29" level=info msg="41497 decisions added"
time="08-03-2023 10:47:29" level=info msg="3 decisions deleted"
time="08-03-2023 10:47:29" level=info msg="1 decision added"
```

So after a service restart, it takes 10 min before Crowdsec is up and running. After that, the decisions are instant.

Hardware opensene box: Intel(R) Celeron(R) CPU J3160 @ 1.60GHz (4 cores, 4 threads)

**Comment by a1ad** [comment]
Hi @mmetc yes of course.

**Comment by mmetc** [comment]
[crowdsec-firewall-bouncer.tar.gz](https://github.com/crowdsecurity/cs-firewall-bouncer/files/10961273/crowdsec-firewall-bouncer.tar.gz)

**Comment by mmetc** [comment]
Just drop this in /usr/local/bin, no configuration change necessary. Thanks

**Comment by a1ad** [comment]
restart at:
time="13-03-2023 22:05:41" level=info msg="Crowdsec v1.4.6-freebsd-c8cb9ac9"

Bouncer ready at:
```
time="13-03-2023 22:05:41" level=info msg="pf table clean-up: /sbin/pfctl -t crowdsec_blacklists -T flush"
time="13-03-2023 22:05:41" level=info msg="Checking pf table: crowdsec_blacklists"
time="13-03-2023 22:05:41" level=info msg="pf initiated for ipv4"
time="13-03-2023 22:05:41" level=info msg="pf table clean-up: /sbin/pfctl -t crowdsec6_blacklists -T flush"
time="13-03-2023 22:05:41" level=info msg="Checking pf table: crowdsec6_blacklists"
time="13-03-2023 22:05:41" level=info msg="pf initiated for ipv6"
time="13-03-2023 22:05:41" level=info msg="Using API key auth"
time="13-03-2023 22:05:41" level=info msg="Processing new and deleted decisions . . ."
time="13-03-2023 22:05:43" level=info msg="1280 decisions deleted"
time="13-03-2023 22:05:43" level=info msg="44906 decisions added"
```
So a couple of seconds instead of 10-15 minutes!!

And tested some real life scenarios (nmap scan from attacking machine) and manual decisions, all working like expected!

Do you need me to test something specific?  I'm going to let the bouncer run for a couple of days anyway.

**Comment by mmetc** [comment]
I'd just like to know if it's stable and if add/remove decisions has an immediate effect.
We could prepare a version by the end of the week.

Thanks again!

**Comment by a1ad** [comment]
2-7sec between add/remove decision and bouncer update.

**Comment by mmetc** [comment]
The 2-7 second delay is due to the update_frequency option, it defaults to 10 seconds. It can be shorter if it does not impact the cpu usage.

**Comment by a1ad** [comment]
oh yeah indeed. So the bouncer is still going strong!

**Comment by mmetc** [comment]
Merged in https://github.com/crowdsecurity/cs-firewall-bouncer/pull/237

**Comment by a1ad** [comment]
Awesome!
