### ISSUE TITLE
Error on installation : iptables init failed: while inserting set in iptables

### ISSUE THREAD

**Issue by ElliotThiebaut** [crowdsecurity/cs-firewall-bouncer#239]
I just installed corwdsec on my Ubuntu 22.04 server and it works fine, but I can't seem to install the Firewall Bouncer.

When I install it via apt I get a error : level=fatal msg="iptables init failed: while inserting set in iptables: exit status 1"
I've searched a little but can't a find the source of the problem.  I have a very simple install of Ubuntu and use UFW as my basic firewall.

Any idea where that comes from ?

**Comment by LaurenceJJones** [comment]
I responded on discord maybe checking out #223 ? it might be firewall by default tries inserting ipv6 rules and you can turn this off within the config file

**Comment by ElliotThiebaut** [comment]
It worked thanks !
