### ISSUE TITLE
API error: access forbidden

### ISSUE THREAD

**Issue by michelep** [crowdsecurity/cs-firewall-bouncer#24]
Following installation instructions, in cs-firewall-bouncer.log i got a lot of:

time="xxx" level=error msg="API error: access forbidden"

and also the crowdstrike_api.log and crowdstrike.log show some problems:

127.0.0.1 - [xxxx] "GET /v1/decisions/stream?startup=false HTTP/1.1 403 688.679µs "cs-firewall-bouncer/v0.0.8-f758a3d7b360ed0adf922f355f13b1efb16610a3" "

time="xxxx" level=error msg="auth api key error: select bouncer: ent: bouncer not found: unable to query"

Any hint?

**Comment by buixor** [comment]
Hello @michelep !

It seems that your bouncer isn't registered to your local api. Can you check :

`cscli bouncers list` -> you should see your bouncer registered. if it's not the case, it might explain the error (you can do `cscli bouncers add MyBouncerName` and add the API key in your bouncer config).

**Comment by michelep** [comment]
Thanks for your reply!

Here's the list of my bouncers:

 cs-firewall-bouncer-gkXvD6bz  127.0.0.1   ✔️     2021-01-19T09:55:08+01:00  cs-firewall-bouncer  v0.0.8-f758a3d7b360ed0adf922f355f13b1efb16610a3 

(The tick symbol is dark grey). Seems that's the bouncer is correctly registered, isn't?

**Comment by buixor** [comment]
yes it seems so.
The error message seems to tell that the key with which the bouncer tries to authenticate isn't found in the database.

Just to check if it's not just the install that went wrong, can you do a `cscli bouncers add MyBouncer` and add the api key in your bouncer's configuration file and then restart the firewall bouncer ? `/etc/crowdsec/cs-firewall-bouncer/cs-firewall-bouncer.yaml`  (you should see a api_key field).

Please let me know :)

**Comment by michelep** [comment]
Thanks, now seems to work correctly. But there's a better way to restart than ps -ax | grep cs-firewall and then cs-firewall.... -c... ?

**Comment by buixor** [comment]
yes, there is systemd unit : `systemctl restart cs-firewall...`
