### ISSUE TITLE
IPTABLES Hash is full, cannot add more elements

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/cs-firewall-bouncer#260]
Just to add documentation and pin an issue to this bouncer.

Due to size of community blocklist and with added support of third party lists user may hit the default limit set by crowdsec-firewall-bouncer-iptables.

To resolve this issue the user must configure a bigger hash set. Open bouncer configuration located normally under `/etc/crowdsec/bouncers/`.  Add the following config:
```yaml
ipset_size: 131072
## this default 65536 * 2
```

This does not exists in the yaml by default so you **MUST** add it.

**Comment by LaurenceJJones** [comment]
@buixor Did you want to still explore increasing the default value?

**Comment by CERT-ARKEA** [comment]
the same opinion, increase the default value (with new blocklists, it is mandatory)

**Comment by LaurenceJJones** [comment]
Reopening issue, to make sure we track any changes we make to cs-firewall
