### ISSUE TITLE
Exclusive lock on the iptables process + 100% CPU usage of iptables ?

### ISSUE THREAD

**Issue by wimg** [crowdsecurity/cs-firewall-bouncer#277]
After starting crowdsec-firewall-bouncer, it becomes impossible to run "iptables -L".

When trying to run it, this is the error that shows :

```shell
# iptables -L
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
#
```

The -w doesn't help, even with a 30 seconds parameter.

It seems the bouncer exclusively locks iptables, so iptables can not be used anymore.

**Comment by wimg** [comment]
Additionally, I just noticed iptables is now using 100% CPU usage on the machines...

**Comment by buixor** [comment]
Hello,

Which version of crowdsec-firewall-bouncer are you using please ?
On which distribution, and with which crowdsec version ?

Thanks, I'm trying to reproduce the bug.

**Comment by wimg** [comment]
Hi,

crowdsec-firewall-bouncer v0.0.26-el7-rpm-fa0e7d25b886aea927c1c3323ba854b5751fc3d1

The bouncer is running on CentOS 7 with package crowdsec-1.4.6-1.el7.x86\_64

After a bit of tinkering, it seems the problem only occurs when using iptables mode, not when using ipset mode.

**Comment by buixor** [comment]
Hello again,

This is very surprising, when using the "iptables" mode of the bouncer, the only thing that should change is that at startup it's going to insert a rule referring to the ipset (and remove it at shutdown). iptables is left untouched when adding/remove decisions etc, the bouncer only interacts with `ipset`.

I didn't manage to reproduce it, so anything would be helpful :)

**Comment by wimg** [comment]
Not sure what to tell you. I tried it again on 2 systems and the result is always the same :-/

**Comment by LaurenceJJones** [comment]
Couldnt replicate,  maybe try disabling prometheus metrics within the bouncer as I saw that uses alot of CPU and might cause locks
