### ISSUE TITLE
Static api_url in config file

### ISSUE THREAD

**Issue by pierrehenrymuller** [crowdsecurity/cs-firewall-bouncer#28]
Hi,

When the install.sh is launched, there is no variable or get params to get the correct url for api_url.
In many servers 8080 is used to listen for web service, if we change the crowdsec port in config.yaml, this bouncer don't follow the parameter.

I suggest to install.sh to parse and get the correct url from config.yaml or user.yaml.

Thanks

**Comment by buixor** [comment]
Hello @pierrehenrymuller 

Sorry for delay ! I guess the wizard of this bouncer is going to stay as is for now, next step would be dpkg/rpm packaging for this component.

**Comment by buixor** [comment]
Hello,

Now that it has been packaged, this should be solved : package checks if cscli is present and register on the user's behalf.

Please let us know if you still have this issue
