### ISSUE TITLE
Error building binary - go-re2 no Go source files

### ISSUE THREAD

**Issue by JasonSanDiego** [crowdsecurity/cs-firewall-bouncer#302]
I'm trying to build from source for Edgerouter-X following the instructions [here](https://discourse.crowdsec.net/t/quick-how-to-for-firewall-bouncer-on-ubiquity-edgerouter/361)

Here's what I get when attempting to build:
```
~/cs-firewall-bouncer$ make release
/bin/sh: 1: [: -gt: unexpected operator
/bin/sh: 3: [: -lt: unexpected operator
/bin/sh: 6: [: -lt: unexpected operator
go build -ldflags "-a -s -w -extldflags '-static' -X 'github.com/crowdsecurity/go-cs-lib/pkg/version.Version=v0.0.28-rc1' -X 'github.com/crowdsecurity/go-cs-lib/pkg/version.BuildDate=2023-06-24_14:52:15' -X 'github.com/crowdsecurity/go-cs-lib/pkg/version.Tag=c8322311d6486a54ff8791930d9735f8700bd296'" -trimpath -tags netgo  -o crowdsec-firewall-bouncer
build github.com/wasilibs/go-re2/internal/cre2: cannot load github.com/wasilibs/go-re2/internal/cre2: no Go source files
make: *** [Makefile:64: binary] Error 1
```

**Comment by mmetc** [comment]
Hi @JasonSanDiego 

the current master has a dependency on the re2 library, normally it should build the wasm version which does not require c++ or libre2-dev.

First, which version of go are you using? "go env GOVERSION" and "go version". There is a version detection which is failing at the top of your text.

To fix your issue you should run

$ go get github.com/crowdsecurity/crowdsec@ebe25d76
$ go mod tidy

This removes the dependency on re2, let me know if it worked

**Comment by mmetc** [comment]
as soon as we have a 1.5.3-rc1 tag on crowdsec, I'll update the dependency on master

**Comment by JasonSanDiego** [comment]
Thank you! I'm running go 1.13, which I take it is pretty old. Unfortunately, Ubuntu 20.04 doesn't have packages for a newer version of go, for whatever reason. I upgraded to 1.20 with a [binary download](https://tecadmin.net/how-to-install-go-on-ubuntu-20-04/) and your instructions worked to build properly.
