### ISSUE TITLE
Default prometheus to false

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/cs-firewall-bouncer#313]
https://github.com/crowdsecurity/cs-firewall-bouncer/blob/5afbe527ad361e578fb1bdf523a2c34c31258149/config/crowdsec-firewall-bouncer.yaml#L55-L56

Should we default to false to not potentially use a port for no reason if the user doesnt know. If they want to be able to get metrics then they can simply come in turn to true and restart service.

**Comment by mmetc** [comment]
done
