### ISSUE TITLE
crowdsec.service: Found dependency on dnsmasq.service/start

### ISSUE THREAD

**Issue by guillaumecotebaladou** [crowdsecurity/cs-firewall-bouncer#326]
Hi,

I have a conflict with crowdsec-firewall-bouncer and dnsmasq.service ordering cycle.
When i comment the before on systemd unit all work again

systemd[1]: crowdsec.service: Found ordering cycle on nss-lookup.target/start
systemd[1]: crowdsec.service: Found dependency on dnsmasq.service/start

$/etc/systemd/system/crowdsec-firewall-bouncer.service
```
[Unit]
Description=The firewall bouncer for CrowdSec
After=syslog.target network.target remote-fs.target nss-lookup.target crowdsec.service
#Before=netfilter-persistent.service

```

**Comment by sabban** [comment]
duplicate https://github.com/crowdsecurity/cs-firewall-bouncer/issues/212
