### ISSUE TITLE
Firewall bouncer not working correctly

### ISSUE THREAD

**Issue by tltglitch** [crowdsecurity/cs-firewall-bouncer#332]
Firewall bouncer will detect and set ban IP as per ban list but IP can still access the website. I am unsure what the issue is:

here is my firewall bouncer config:
```                                              
mode: iptables
piddir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
api_url: http://127.0.0.1:8080/
api_key: xxxx
disable_ipv6: false
#if present, insert rule in those chains
iptables_chains:
  - INPUT
  - FORWARD
#  - DOCKER-USER
```

Note: this is a none docker application

**Comment by LaurenceJJones** [comment]
Can you provide the output of `iptables -L` as there must be a rule over ours OR something has flushed the chains whilst the bouncer was running and it hasnt reinserted it.

**Comment by LaurenceJJones** [comment]
Add question label as we wait for OP to answer
