### ISSUE TITLE
[metrics] Investigate nftables

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/cs-firewall-bouncer#334]
Just adding an issue here as I had it multiple times:

The way we collect metrics on nftables is resource heavy and I had multiple complaints from users that if they enable it their CPU usage is pinned 100%.

I want to add this issue to keep track and one day once we have time to add improvement.

**Comment by LaurenceJJones** [comment]
add a configuration option https://github.com/crowdsecurity/cs-firewall-bouncer/blob/af6e7e25822c2b1a02168b99ebbf8458bc6728e5/pkg/metrics/metrics.go#L9

**Comment by ne20002** [comment]
@LaurenceJJones 
You may also look at #316. The high CPU load is still not fixed.
