### ISSUE TITLE
Install and/or upgrade fails if crowdsec is not running

### ISSUE THREAD

**Issue by WagenerHAW** [crowdsecurity/cs-firewall-bouncer#337]
It seems, that the firewall-bouncer requires crowdsec to run. I had an upgrade error because somehow crowdsec was not running when the bouncer updated. So a change in the systemd from After to Requires makes sense?!

[Unit]
Description=The firewall bouncer for CrowdSec
After=syslog.target network.target remote-fs.target nss-lookup.target
Requires=crowdsec.service
Before=netfilter-persistent.service

**Comment by sabban** [comment]
duplicate with https://github.com/crowdsecurity/cs-firewall-bouncer/issues/212
