### ISSUE TITLE
Installation on  Ubuntu 23.04 (lunar) not available

### ISSUE THREAD

**Issue by mr-bolle** [crowdsecurity/cs-firewall-bouncer#342]
Hi, 

i would install the firewall bouncer on Ubuntu 2023.4

https://doc.crowdsec.net/docs/next/getting_started/install_crowdsec##install-our-repositories
`curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash` 

> sudo apt update 
```
Ign:5 https://packagecloud.io/crowdsec/crowdsec/ubuntu lunar InRelease
Err:6 https://packagecloud.io/crowdsec/crowdsec/ubuntu lunar Release
  404  Not Found [IP: 13.57.106.95 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/crowdsec/crowdsec/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

There is no packages avaiable
> https://packagecloud.io/app/crowdsec/crowdsec/search?dist=ubuntu%2Flunar

**Comment by Eatric** [comment]
Agree, and cannot be installed by wizard.sh file always exit code

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

Closing issue as we have a new `any:any` installation script found:

```
curl -s https://install.crowdsec.net | sudo sh
```

Please reopen issue if the problem still exists after executing the script above.
