### ISSUE TITLE
No Fedora 39 build

### ISSUE THREAD

**Issue by SecT0uch** [crowdsecurity/cs-firewall-bouncer#362]
/kind packaging

Is it possible to add a Fedora 39 build to packagecloud ?

`crowdsec` is available, but not the firewall bouncer (interested in `-nftables`)

**Comment by LaurenceJJones** [comment]
Link to upstream ticket to track `any/any` inclusion:

https://github.com/crowdsecurity/crowdsec/issues/2818

**Comment by LaurenceJJones** [comment]
Classing as resolved, however, if you used the older installation method you must re run the following command:

```
curl -s https://install.crowdsec.net | sudo sh
```

This will force the new naming schemas on the rpm any:any install
