### ISSUE TITLE
Errors were encountered while processing:  crowdsec-firewall-bouncer-iptables

### ISSUE THREAD

**Issue by modem7** [crowdsecurity/cs-firewall-bouncer#378]
### What happened?

doing apt update, it fails

### What did you expect to happen?

for it not to fail

### How can we reproduce it (as minimally and precisely as possible)?

sudo aptitude update && sudo aptitude safe-upgrade -y

### Anything else we need to know?

```console
❯ sudo apt install crowdsec-firewall-bouncer-iptables
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  crowdsec-firewall-bouncer-iptables
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 3271 kB of archives.
After this operation, 12.5 MB of additional disk space will be used.
Get:1 https://packagecloud.io/crowdsec/crowdsec/ubuntu jammy/main arm64 crowdsec-firewall-bouncer-iptables arm64 0.0.29 [3271 kB]
Fetched 3271 kB in 1s (4277 kB/s)
Selecting previously unselected package crowdsec-firewall-bouncer-iptables.
(Reading database ... 137434 files and directories currently installed.)
Preparing to unpack .../crowdsec-firewall-bouncer-iptables_0.0.29_arm64.deb ...
Unpacking crowdsec-firewall-bouncer-iptables (0.0.29) ...
Setting up crowdsec-firewall-bouncer-iptables (0.0.29) ...
cscli/crowdsec is present, generating API key
API Key successfully created
Created symlink /etc/systemd/system/multi-user.target.wants/crowdsec-firewall-bouncer.service → /etc/systemd/system/crowdsec-firewall-bouncer.service.
Job for crowdsec-firewall-bouncer.service failed because the control process exited with error code.
See "systemctl status crowdsec-firewall-bouncer.service" and "journalctl -xeu crowdsec-firewall-bouncer.service" for det
ails.
dpkg: error processing package crowdsec-firewall-bouncer-iptables (--configure):
 installed crowdsec-firewall-bouncer-iptables package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 crowdsec-firewall-bouncer-iptables
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### version

remediation component version:

<details>

```console
version: v0.0.29-debian-pragmatic-arm64-9594360ca83272d5c15ed1c343a6d96868d83cbc
BuildDate: 2024-08-16_15:52:03
GoVersion: 1.22.2
Platform: linux
```

</details>

### crowdsec version

crowdsec version:

<details>

```console
❯ crowdsec --version
version: v1.6.2-debian-pragmatic-arm64-16bfab86
Codename: alphaga
BuildDate: 2024-05-31_09:15:42
GoVersion: 1.22.2
Platform: linux
libre2: C++
User-Agent: crowdsec/v1.6.2-debian-pragmatic-arm64-16bfab86-linux
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
❯ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

❯ uname -a
Linux uptimekuma 6.5.0-1027-oracle #27~22.04.1-Ubuntu SMP Sat Jul 20 13:14:31 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

**Comment by modem7** [comment]
```console
sudo journalctl -xeu crowdsec-firewall-bouncer.service
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit crowdsec-firewall-bouncer.service has finished with a failure.
░░
░░ The job identifier is 3751013 and the job result is failed.
Aug 17 06:13:37 uptimekuma systemd[1]: crowdsec-firewall-bouncer.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ Automatic restarting of the unit crowdsec-firewall-bouncer.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Aug 17 06:13:37 uptimekuma systemd[1]: Stopped The firewall bouncer for CrowdSec.
░░ Subject: A stop job for unit crowdsec-firewall-bouncer.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A stop job for unit crowdsec-firewall-bouncer.service has finished.
░░
░░ The job identifier is 3751101 and the job result is done.
Aug 17 06:13:37 uptimekuma systemd[1]: Starting The firewall bouncer for CrowdSec...
░░ Subject: A start job for unit crowdsec-firewall-bouncer.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit crowdsec-firewall-bouncer.service has begun execution.
░░
░░ The job identifier is 3751101.
```

**Comment by aaronjrodrigues** [comment]
experiencing the same issue

**Comment by blotus** [comment]
Hello,

Can you provide the content of `/var/log/crowdsec-firewall-bouncer.log` ?

**Comment by LaurenceJJones** [comment]
It could be that you declined the systemd service file update and the files have now moved?

```
Configuration file '/etc/systemd/system/crowdsec-firewall-bouncer.service'
==> Modified (by you or by a script) since installation.
==> Package distributor has shipped an updated version.
What would you like to do about it ?  Your options are:
Y or I  : install the package maintainer's version
N or O  : keep your currently-installed version
D     : show the differences between the versions
Z     : start a shell to examine the situation
The default action is to keep your current version.
*** crowdsec-firewall-bouncer.service (Y/I/N/O/D/Z) [default=N] ? D
-ExecStart=/usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
-ExecStartPre=/usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -t
+ExecStart=/usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
+ExecStartPre=/usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -t
```

**Comment by aaronjrodrigues** [comment]
After experiencing the error that modem7 encountered I uninstalled both crowdsec and the firewall bouncer hoping the reinstall would help however the crowdsec installation goes fine but the firewall bouncer's install doesn't go well

`ubuntu@nimbus2000:~$ sudo apt install crowdsec-firewall-bouncer-iptables
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ipset libipset13
The following NEW packages will be installed:
  crowdsec-firewall-bouncer-iptables ipset libipset13
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3367 kB of archives.
After this operation, 12.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package libipset13:arm64.
(Reading database ... 101850 files and directories currently installed.)
Preparing to unpack .../libipset13_7.15-1build1_arm64.deb ...
Unpacking libipset13:arm64 (7.15-1build1) ...
Selecting previously unselected package ipset.
Preparing to unpack .../ipset_7.15-1build1_arm64.deb ...
Unpacking ipset (7.15-1build1) ...
Selecting previously unselected package crowdsec-firewall-bouncer-iptables.
Preparing to unpack .../crowdsec-firewall-bouncer-iptables_0.0.29_arm64.deb ...
Unpacking crowdsec-firewall-bouncer-iptables (0.0.29) ...
Setting up libipset13:arm64 (7.15-1build1) ...
Setting up ipset (7.15-1build1) ...
Setting up crowdsec-firewall-bouncer-iptables (0.0.29) ...
FATA[0000] unable to read config file: while reading yaml file: open /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml: no such file or directory 
Failed to get unit file state for crowdsec-firewall-bouncer.service: No such file or directory
Unit crowdsec-firewall-bouncer.service does not exist, proceeding anyway.
Failed to enable unit: Unit file crowdsec-firewall-bouncer.service does not exist.
dpkg: error processing package crowdsec-firewall-bouncer-iptables (--configure):
 installed crowdsec-firewall-bouncer-iptables package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
Errors were encountered while processing:
 crowdsec-firewall-bouncer-iptables
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by aaronjrodrigues** [comment]
Is there any way to completely remove both crowdsec and firewall bouncer so that the next install can be treated like a fresh install.

**Comment by LaurenceJJones** [comment]
> Is there any way to completely remove both crowdsec and firewall bouncer so that the next install can be treated like a fresh install.

With the `apt` package manager to "fully" uninstall, you use the `purge` command, using "uninstall" command tell `apt` that the configuration files will still exists on a `apt install`

**Comment by aaronjrodrigues** [comment]
thank you so much!! that fixed it!

**Comment by modem7** [comment]
> It could be that you declined the systemd service file update and the files have now moved?
> 
> ```
> Configuration file '/etc/systemd/system/crowdsec-firewall-bouncer.service'
> ==> Modified (by you or by a script) since installation.
> ==> Package distributor has shipped an updated version.
> What would you like to do about it ?  Your options are:
> Y or I  : install the package maintainer's version
> N or O  : keep your currently-installed version
> D     : show the differences between the versions
> Z     : start a shell to examine the situation
> The default action is to keep your current version.
> *** crowdsec-firewall-bouncer.service (Y/I/N/O/D/Z) [default=N] ? D
> -ExecStart=/usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
> -ExecStartPre=/usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -t
> +ExecStart=/usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
> +ExecStartPre=/usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -t
> ```
> 
> Could you also run `systemctl cat crowdsec-firewall-bouncer.service`
> 
> It seems there lots of binaries everywhere but also symlinked
> 
> ```
> 07:51:26 root@laurencejones ~ → /usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -V
> version: v0.0.29-debian-pragmatic-amd64-9594360ca83272d5c15ed1c343a6d96868d83cbc
> BuildDate: 2024-08-16_15:51:54
> GoVersion: 1.22.2
> Platform: linux
> 07:51:29 root@laurencejones ~ → /usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -V
> version: v0.0.29-debian-pragmatic-amd64-9594360ca83272d5c15ed1c343a6d96868d83cbc
> BuildDate: 2024-08-16_15:51:54
> GoVersion: 1.22.2
> Platform: linux
> ```

That's what I thought first, but I've done apt purge a few times since, but no go.

```console
❯ sudo systemctl cat crowdsec-firewall-bouncer.service
# /etc/systemd/system/crowdsec-firewall-bouncer.service
[Unit]
Description=The firewall bouncer for CrowdSec
After=syslog.target network.target remote-fs.target nss-lookup.target crowdsec.service

[Service]
Type=notify
ExecStart=/usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
ExecStartPre=/usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -t
ExecStartPost=/bin/sleep 0.1
Restart=always
RestartSec=10
LimitNOFILE=65536
# don't send a termination signal to the children processes,
# because the iptables backend needs to run ipset multiple times to properly shutdown
KillMode=mixed

[Install]
WantedBy=multi-user.target
```

[crowdsec-firewall-bouncer.zip](https://github.com/user-attachments/files/16657859/crowdsec-firewall-bouncer.zip)

**Comment by LaurenceJJones** [comment]
It seems the configured LAPI is `127.0.0.1:8080` is that correct?

if so it seems it not running or there a firewall connection in the way?

```
time="2024-08-19T09:32:52+01:00" level=error msg="auth-api: auth with api key failed return nil response, error: dial tcp 127.0.0.1:8080: connect: connection refused"
time="2024-08-19T09:32:52+01:00" level=error msg="Get \"http://127.0.0.1:8080/v1/decisions/stream?startup=true\": dial tcp 127.0.0.1:8080: connect: connection refused"
```

**Comment by modem7** [comment]
```console
❯ sudo service crowdsec status
● crowdsec.service - Crowdsec agent
     Loaded: loaded (/lib/systemd/system/crowdsec.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-08-19 09:41:22 BST; 24s ago
   Main PID: 3376846 (crowdsec)
      Tasks: 20 (limit: 28690)
     Memory: 123.1M
        CPU: 5.017s
     CGroup: /system.slice/crowdsec.service
             ├─3376846 /usr/bin/crowdsec -c /etc/crowdsec/config.yaml
             └─3376863 /usr/lib/crowdsec/plugins/notification-slack

Aug 19 09:41:18 uptimekuma systemd[1]: Starting Crowdsec agent...
Aug 19 09:41:22 uptimekuma systemd[1]: Started Crowdsec agent.
❯ sudo service crowdsec-firewall-bouncer status
● crowdsec-firewall-bouncer.service - The firewall bouncer for CrowdSec
     Loaded: loaded (/etc/systemd/system/crowdsec-firewall-bouncer.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-08-19 09:41:33 BST; 17s ago
   Main PID: 3377111 (crowdsec-firewa)
      Tasks: 12 (limit: 28690)
     Memory: 21.4M
        CPU: 18.748s
     CGroup: /system.slice/crowdsec-firewall-bouncer.service
             ├─3377111 /usr/bin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
             └─3398425 /usr/sbin/ipset -exist add crowdsec-blacklists 80.211.224.194 timeout 86388

Aug 19 09:41:29 uptimekuma systemd[1]: Starting The firewall bouncer for CrowdSec...
Aug 19 09:41:33 uptimekuma systemd[1]: Started The firewall bouncer for CrowdSec.
```
