### ISSUE TITLE
Version information via cli

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/cs-firewall-bouncer#40]
For configuration management we need to get the version from cs-firewall-bouncer. At this time, there is no option like `cs-firewall-bouncer --version`. I can use a regular expression to get the desired info, but it's not that great solution.
Is it possible to add this simple but useful feature?

**Comment by sbz** [comment]
Hi @Lamera, I think you could use the new`-V` for that. It was added in my PR #41

**Comment by buixor** [comment]
merged, will close at next release :)
