### ISSUE TITLE
Debian/Ubuntu packages missing?

### ISSUE THREAD

**Issue by saz** [crowdsecurity/cs-firewall-bouncer#59]
Looking at the [documentation](https://hub.crowdsec.net/author/crowdsecurity/bouncers/cs-firewall-bouncer#installation), it should be possible to install the crowdsec-firewall-bouncer from the crowdsec repository.

Adding the repo and searching for package names containing crowdsec, there's only one result, but none for the firewall bouncer.
Looking at https://s3-eu-west-1.amazonaws.com/crowdsec.debian.pragmatic/buster/dists/buster/main/binary-amd64/Packages, there's only the crowdsec package listed.

**Comment by buixor** [comment]
Hello,

Sorry, the documentation was merged a bit too early :sweat_smile: 
The new packages (with the support from packagecloud.io) will be made public early next week and will include centos/debian, but we need to do some final tests before GA !

Please bear with us a few more days ;)

**Comment by saz** [comment]
@buixor Will do, thanks :-)

**Comment by buixor** [comment]
it has been published, forgot to answer ;)
