### ISSUE TITLE
bad upgrade from v0.0.12 to v0.0.13 (service name change)

### ISSUE THREAD

**Issue by gerbier** [crowdsecurity/cs-firewall-bouncer#65]
Hello
I was using cs-firewall-bouncer-v0.0.12. I have downloaded crowdsec-firewall-bouncer-v0.0.13 and I have run  sudo ./upgrade.sh
but it display an error because the service was changed from cs-firewall-bouncer to crowdsec-firewall-bouncer.
You should modify the upgrade.sh shell or the release notes to alert users.

**Comment by buixor** [comment]
Hello,

With packaging, there is now only one package (-nftables or -iptables) and install/upgrade script should be kept for corner cases !
