### ISSUE TITLE
deny_log produce invalid iptables command

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/cs-firewall-bouncer#69]
When enabling `deny_log`, we produce an invalid iptables command that looks like this:
` iptables -I INPUT -m set --match-set foobar src --log-prefix pouet -j LOG`

This gives `iptables v1.8.2 (nf_tables): unknown option "--log-prefix` because the `--log-prefix` *MUST BE* after the `-j LOG`.

We should generate ` iptables -I INPUT -m set --match-set foobar src -j LOG --log-prefix pouet` instead.

**Comment by lol-deb** [comment]
Thank you for that @blotus!
